[tools]
python = "3.11"
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.test]
run = "uv run python -m pytest"
description = "Run tests"

[tasks.lint]
run = "uv run ruff check ."
description = "Run ruff linter"

[tasks.format]
run = "uv run ruff format ."
description = "Format code"

[tasks.format-check]
run = "uv run ruff format --check ."
description = "Check code formatting without modifying files"

[tasks.typecheck]
run = "uv run pyright"
description = "Run pyright type checker"

[tasks.check]
depends = ["lint", "format-check", "typecheck", "test"]
description = "Run all checks (lint, format-check, typecheck, test)"

[tasks.reconcile]
run = "uv run ledger-reconcile"
description = "Run ledger-reconcile CLI"

[tasks.preview-sexp-tests]
run = "uv run python scripts/generate_sexp_test_preview.py"
description = "Generate HTML preview of S-expression test fixtures"
