[tools]
python = "3.11"
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.test]
run = "uv run python -m pytest"
description = "Run tests"

[tasks.lint]
run = "uv run ruff check ."
description = "Run ruff linter"

[tasks.format]
run = "uv run ruff format ."
description = "Format code"

[tasks.format-check]
run = "uv run ruff format --check ."
description = "Check code formatting without modifying files"

[tasks.typecheck]
run = "uv run pyright"
description = "Run pyright type checker"

[tasks.deptry]
run = "uv run deptry ."
description = "Check for unused dependencies"

[tasks.generate-test-previews]
run = "uv run python tests/generate_all_previews.py"
description = "Generate HTML previews for all test cases"

[tasks.check]
depends = [
    "lint",
    "format-check",
    "typecheck",
    "deptry",
    "test",
    "generate-test-previews",
]
description = "Run all checks (lint, format-check, typecheck, test) and generate test previews"

[tasks.reconcile]
run = "uv run ledger-reconcile"
description = "Run ledger-reconcile CLI"
