[tools]
python = "3.13.5"
uv = "0.7.12"
node = "24.3.0"          # for gh-pages
"npm:gh-pages" = "6.3.0"

[settings]
python.uv_venv_auto = true

[tasks.test]
run = "uv run python -m pytest"
description = "Run tests"

[tasks.lint]
run = "uv run ruff check ."
description = "Run ruff linter"

[tasks.format]
run = "uv run ruff format ."
description = "Format code"

[tasks.format-check]
run = "uv run ruff format --check ."
description = "Check code formatting without modifying files"

[tasks.typecheck]
run = "uv run pyright"
description = "Run pyright type checker"

[tasks.deptry]
run = "uv run deptry ."
description = "Check for unused dependencies"

[tasks.generate-test-previews]
run = "uv run python tests/generate_all_previews.py"
description = "Generate HTML previews for all test cases"

[tasks.publish-test-previews]
env = { "CACHE_DIR" = "{{ xdg_cache_home }}" }
run = "gh-pages -d tests/preview"
depends = ["generate-test-previews"]
description = "Publish test previews to GH Pages"

[tasks.check]
depends = [
    "lint",
    "format-check",
    "typecheck",
    "deptry",
    "test",
    "generate-test-previews",
]
description = "Run all checks (lint, format-check, typecheck, test) and generate test previews"

[tasks.reconcile]
run = "uv run ledger-reconcile"
description = "Run ledger-reconcile CLI"

[tasks.coverage]
run = "mise run test -- --cov=ledger_reconcile --cov-report=term-missing"

[tasks.coverage-html]
run = "rm -rf htmlcov && mise run test -- --cov=ledger_reconcile --cov-report=html"
